### ISSUE TITLE
In some IPSAN, get_target_port_group_support should be called before get_target_port_group

### ISSUE THREAD

**Issue by wangwang3210** [openSUSE/multipath-tools#33]
In function get_alua_info from libmultipath/prioritizers/alua.c.
For now logic, get_alua_info call get_target_port_group first, if get_target_port_group return value tpg >= 0,  get_target_port_group_support will not be called, this logic is commited in d7ee31debda0cc7b2c43b8ffdad9211fa8fa60a8.

When I use multipath to visit a IPSAN,  I modified my code, calling get_target_port_group_support after calling get_target_port_group even if return value tpg >= 0, actually,  get_target_port_group_support return TPGS_NONE, it is weird, it could get TPG while it does not support TPG.

In common logic, we should get capability before we get some featurn value, I think it is more reasonable to call get_target_port_group_support first, if TPG is suported, then call get_target_port_group.
thanks a lot.

**Comment by wangwang3210** [comment]
It is not found that which function should call first in SCSI protocol manual.

**Comment by hreinecke** [comment]
Well, problem is that get_target_port_group_support is not guaranteed to return anything sensible; some implementations will return '0' here, declaring everything is 'vendor specific', yet support get_target_port_groups.
So I'm afraid this is not going to help us.

**Comment by wangwang3210** [comment]
> Well, problem is that get_target_port_group_support is not guaranteed to return anything sensible; some implementations will return '0' here, declaring everything is 'vendor specific', yet support get_target_port_groups.
> So I'm afraid this is not going to help us.

Thanks for your help, very helpful.

**Comment by mwilck** [comment]
Note: in `detect_alua()`, we call `get_target_port_group_support()` first, then `get_target_port_group()`, and finally `get_asymmetric_access_state()`, and only **if they all succeed** (which means retcode > 0 for `get_target_port_group_support()`) we set `pp->tpgs` to anything other than `TPGS_NONE`. Moreover, in `select_prio()`, we reset the prioritizer from "alua" to "const" if `detect_alua()` fails. 

In other words, the "alua" prioritizer isn't used if the TPGS bits from the INQUIRY data are 0 or if ALUA calls fails, not even if "alua" is explicitly configured by the user. 

OTOH, it also means that if the alua prioritizer is selected, we have good reason to expect that ALUA calls succeed. Therefore, in `get_alua_info()`, it's reasonable to call `get_target_port_group()` without inquiring TPGS before. Only if the RTPG call fails, we check TPGS once more. It can be argued that  this is superfluous - it can only happen if an existing device suddenly ceases to support ALUA, which would be highly unexpected. But it's an error handling code path, and might help understand what was going wrong if that situation actually occurs.
