### ISSUE TITLE
the performance of small I/Os

### ISSUE THREAD

**Issue by daringpig** [openSUSE/multipath-tools#9]
Respected Maintainers, 
Sorry to bother you! I really admire you for your excellent work on multipath-tools. I am a storage fan too, although I'm just a green hand. Now, there are some challenging problems about multipath-tools in front of me, and I am eager to get your help.
Here is the question. My storage server is a dual-controller machine with RHEL 7. You know, in certain circumstances, they call it two-storage-processor(SP). I map one LUN out by targetcli(which used to configure the LIO) through the two SPs independently, and manage the mapped devices by multipath software in another host server. Logged in through iscsiadm, I get two(or more) devices in the host server, just name them /dev/sdc and /dev/sdd for example, and multipath combines them into one under /dev/mapper, just name it /dev/mapper/mpathb for example. Then I write some data into /dev/mapper/mpathb in the unit of 4KB, and find the bandwidth is not very high. If this could be accepted, the following thing maybe not. When I write some data into /dev/sdc, the bandwidth is much higher. Then I change the storage server, use a dual-controller machine of EMC instead, the result is much better. the difference of bandwidth between /dev/sdc (I call it iSCSI LUN) and /dev/mapper/mpathb (I call it multipath LUN)is almost negligible. And another phenomenon is that even with my own dual-controller machine, the the difference of bandwidth between the iSCSI LUN and the multipath LUN get reduced as the unit of I/O becomes bigger, like 1MB.
During the test, the host server and its configuration keep same. So I think the storage is the point, especially the LIO target driver, but I don't know how and why. 
I trace the I/O, and find when writing the iSCSI LUN -- /dev/sdc, the small I/Os(like 4KB) combine into a bigger one by the Linux I/O Elevator Scheduler(it's the elv_merge() function in kernel for specific) in the host server, but when it occur to the multipath LUN -- /dev/mapper/mpathb, the small I/Os don't combine.
So, I want to optimize the performance of small I/Os, but don't know how to, because I don't know why.

Can you help me with the questions? I will appreciate it very much.Thank you.

**Comment by mwilck** [comment]
Sorry for answering so late. Your question is not about multipath-tools, it's about the kernel's dm-multipath driver, the block layer, and actually, as you figured out already, the LIO target. multipath-tools is only for administering the multipath stack, it has no influence on the performance.

Some points to check:

 - which IO scheduler was used in the bare SCSI vs. multipath case?
 - which path selection algorithm and path grouping policy did you use in your multipath setup?
